#!/usr/bin/env python3
"""
reference___NAME__.py — staged template (read-only). Generated by skill-adapter
from external skill source. Copy to
/job/reproducibility/generated_scripts/__NAME___<YYYYMMDD-HHMMSS>.py and
customize before running.

DRAFT — every TODO[skill-adapter] marker below MUST be resolved by hand.
"""
import json
import sys
from pathlib import Path

STAGE_DIR     = Path("/job/stage/__NAME__")
ANALYSIS_DIR  = Path("/job/analysis/__NAME__")
GENERATED_DIR = Path("/job/reproducibility/generated_scripts")


def main():
    if not STAGE_DIR.is_dir():
        sys.stderr.write(f"missing input: {STAGE_DIR}\n")
        sys.exit(1)
    ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

    # ── BEGIN ADAPTED BODY ─────────────────────────────────────────
    # Static rewrite of the external skill's entry script. Lines are
    # commented out — uncomment and edit only after replacing every
    # TODO[skill-adapter] flag (cross-reference unsafe_findings.json).
    #
__BODY_AS_COMMENT__
    # ── END ADAPTED BODY ───────────────────────────────────────────

    meta = {
        "skill": "__NAME__",
        "packages": {},
        "parameters": {},
        "random_seed": 42,
        "decisions": "Adapted by skill-adapter; resolve TODO markers above before use.",
    }
    (ANALYSIS_DIR / "__NAME___meta.json").write_text(
        json.dumps(meta, indent=2, sort_keys=True)
    )


if __name__ == "__main__":
    main()
